// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabPageContacts;
lv_obj_t * ui_Contacts;
lv_obj_t * ui_ContactMessages;
lv_obj_t * ui_TabPageChannels;
lv_obj_t * ui_Channels;
lv_obj_t * ui_ChannelMessages;
void ui_event_AutoLight(lv_event_t * e);
lv_obj_t * ui_AutoLight;
lv_obj_t * ui____initial_actions0;

lv_obj_t * ui_DimOverlay;
lv_obj_t * ui_TabPageHome;
lv_obj_t * ui_ValueDate;
lv_obj_t * ui_ValueTime;
lv_obj_t * ui_TabPageSettings;
lv_obj_t * ui_DayLight;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
