// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: Buttons

#ifndef _BUTTONS_UI_H
#define _BUTTONS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "defines.h"
#include "../lvgl/lvgl.h"

#include "../fonts/fonts.h"
#include "../../include/configuration.h"

#include "ui_helpers.h"

// main
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Main;
#ifdef SHOW_TOP_BAR
extern lv_obj_t * ui_TopBar;
extern lv_obj_t * ui_TopBarLeftContainer;
    #ifdef USE_MODULE_CONTROLS
    extern lv_obj_t * ui_ControlsStatus;
    #endif
extern lv_obj_t * ui_TopBarMiddleContainer;
extern lv_obj_t * ui_TopBarRightContainer;
    #ifdef ENABLE_RTC_CLOCK
    extern lv_obj_t * ui_DateTime;
    #endif
#endif

#ifdef USE_MAIN_TAB_VIEW
    extern lv_obj_t * ui_MainTabView;
#endif

// Controls
#ifdef USE_MODULE_CONTROLS
    extern lv_obj_t * ui_ViewControls;
    extern lv_obj_t * ui_ContainerControls1;
    extern lv_obj_t * ui_Panel1;
    extern lv_obj_t * ui_ControlLabel1;
    extern lv_obj_t * ui_ControlImage1;
    extern lv_obj_t * ui_Panel2;
    extern lv_obj_t * ui_ControlLabel2;
    extern lv_obj_t * ui_ControlImage2;
    extern lv_obj_t * ui_Panel3;
    extern lv_obj_t * ui_ControlLabel3;
    extern lv_obj_t * ui_ControlImage3;
    extern lv_obj_t * ui_ContainerControls2;
    extern lv_obj_t * ui_Panel4;
    extern lv_obj_t * ui_ControlLabel4;
    extern lv_obj_t * ui_ControlImage4;
    extern lv_obj_t * ui_Panel5;
    extern lv_obj_t * ui_ControlLabel5;
    extern lv_obj_t * ui_ControlImage5;
    extern lv_obj_t * ui_Panel6;
    extern lv_obj_t * ui_ControlLabel6;
    extern lv_obj_t * ui_ControlImage6;
    extern lv_obj_t * ui_ContainerControls3;
    extern lv_obj_t * ui_Panel7;
    extern lv_obj_t * ui_ControlLabel7;
#endif

// Settings
#ifdef USE_MODULE_SETTINGS
    extern lv_obj_t * ui_ViewSettings;
    #ifdef USE_MODULE_CONTROLS
        extern lv_obj_t * ui_WaitRelay;
    #endif
#endif

extern lv_obj_t * ui____initial_actions0;

#ifdef USE_MODULE_CONTROLS
LV_IMG_DECLARE(ui_img_icon_switch_png);    // assets\icon_switch.png
LV_IMG_DECLARE(ui_img_b_led_bar_png);    // assets\b_led_bar.png
LV_IMG_DECLARE(ui_img_b_slim_led_bar_png);    // assets\b_slim_led_bar.png
LV_IMG_DECLARE(ui_img_b_led_lights_png);    // assets\b_led_lights.png
LV_IMG_DECLARE(ui_img_b_lights_left_png);    // assets\b_lights_left.png
LV_IMG_DECLARE(ui_img_b_lights_right_png);    // assets\b_lights_right.png
LV_IMG_DECLARE(ui_img_b_rear_lights_png);    // assets\b_rear_lights.png
#endif
#ifdef USE_HOME_PAGE
    LV_IMG_DECLARE(ui_img_icon_home_png);    // assets\icon_home.png
#endif
#ifdef USE_MODULE_SETTINGS
    LV_IMG_DECLARE(ui_img_icon_settings_png);    // assets\icon_settings.png
#endif

#ifdef USE_MODULE_CONTROLS    
    extern void onWaitRelayPressed(bool pressed);

    extern void ui_event_Panel(lv_event_t * e);
    extern void onMainBar(lv_event_t * e);
    extern void onLeftLeds(lv_event_t * e);
    extern void onRightLeds(lv_event_t * e);
    extern void onRearLeds(lv_event_t * e);
    extern void onRoofBar(lv_event_t * e);
    extern void onRoofLeds(lv_event_t * e);
    extern void onStrobeLights(lv_event_t * e);
#endif

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
