// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "../fonts/fonts.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void setNightMode(bool night);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPageContacts;
extern lv_obj_t * ui_Contacts;
extern lv_obj_t * ui_ContactMessages;
extern lv_obj_t * ui_TabPageChannels;
extern lv_obj_t * ui_Channels;
extern lv_obj_t * ui_ChannelMessages;
extern lv_obj_t * ui_TabPageSettings;
void ui_event_AutoLight(lv_event_t * e);
extern lv_obj_t * ui_AutoLight;
extern lv_obj_t * ui____initial_actions0;

extern lv_obj_t * ui_DimOverlay;
extern lv_obj_t * ui_TabPageHome;
extern lv_obj_t * ui_ValueDate;
extern lv_obj_t * ui_ValueTime;
extern lv_obj_t * ui_TabPageSettings;
extern lv_obj_t * ui_DayLight;

extern void onDayLightPressed(bool pressed);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
