// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

static void scroll_begin_event(lv_event_t* e)
{
    /*Disable the scroll animations. Triggered when a tab button is clicked */
    if (lv_event_get_code(e) == LV_EVENT_SCROLL_BEGIN) {
        lv_anim_t* a = (lv_anim_t*)lv_event_get_param(e);
        if (a)  a->time = 0;

    }
}

void event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(code == LV_EVENT_VALUE_CHANGED) {
        if (target == ui_DayLight) {
            onDayLightPressed(lv_obj_get_state(target) & LV_STATE_CHECKED);
        }
    }
}

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);

    lv_obj_add_event_cb(lv_tabview_get_content(ui_TabView1), scroll_begin_event,LV_EVENT_SCROLL_BEGIN, NULL);
    lv_obj_clear_flag(lv_tabview_get_content(ui_TabView1), LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_set_width(ui_TabView1, 800);
    lv_obj_set_height(ui_TabView1, 480);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x424242),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &lv_font_arial_18,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);

    #if defined(LANG_EN)
    ui_TabPageHome = lv_tabview_add_tab(ui_TabView1, "Home");
    #elif defined(LANG_GR)
    ui_TabPageHome = lv_tabview_add_tab(ui_TabView1, "Αρχική");
    #endif   

    ui_ValueDate = lv_label_create(ui_TabPageHome);
    lv_obj_set_width(ui_ValueDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueDate, 0);
    lv_obj_set_y(ui_ValueDate, -165);
    lv_obj_set_align(ui_ValueDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueDate, "--- --/--/----");
    lv_obj_set_style_text_color(ui_ValueDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueDate, &lv_font_arial_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueTime = lv_label_create(ui_TabPageHome);
    lv_obj_set_width(ui_ValueTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValueTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValueTime, 0);
    lv_obj_set_y(ui_ValueTime, -100);
    lv_obj_set_align(ui_ValueTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValueTime, "--:--");
    lv_obj_set_style_text_color(ui_ValueTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueTime, &lv_font_arial_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    #if defined(LANG_EN)
    ui_TabPageContacts = lv_tabview_add_tab(ui_TabView1, "Contacts");
    #elif defined(LANG_GR)
    ui_TabPageContacts = lv_tabview_add_tab(ui_TabView1, "Επαφές");
    // Prevent scrolling
    lv_obj_set_scrollbar_mode(ui_TabPageContacts, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(ui_TabPageContacts, LV_OBJ_FLAG_SCROLLABLE);
    #endif    

    ui_Contacts = lv_list_create(ui_TabPageContacts);
    //lv_list_set_options(ui_Contacts, "Contact", LV_list_MODE_NORMAL);
    lv_obj_set_width(ui_Contacts, 250);
    lv_obj_set_height(ui_Contacts, 400);
    lv_obj_set_x(ui_Contacts, -274);
    lv_obj_set_y(ui_Contacts, 0);
    lv_obj_set_align(ui_Contacts, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_opa(ui_Contacts, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_Contacts, 0, 0);
    lv_obj_set_style_outline_width(ui_Contacts, 0, 0);
    lv_obj_set_style_shadow_width(ui_Contacts, 0, 0);
    //lv_obj_set_scrollbar_mode(ui_Contacts, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_opa(ui_Contacts, LV_OPA_TRANSP, LV_PART_ITEMS);
    lv_obj_set_style_border_width(ui_Contacts, 0, LV_PART_ITEMS);

    ui_ContactMessages = lv_list_create(ui_TabPageContacts);
    //lv_list_set_options(ui_ContactMessages, "Contact", LV_list_MODE_NORMAL);
    lv_obj_set_width(ui_ContactMessages, 500);
    lv_obj_set_height(ui_ContactMessages, 400);
    lv_obj_set_x(ui_ContactMessages, 124);
    lv_obj_set_y(ui_ContactMessages, 0);
    lv_obj_set_align(ui_ContactMessages, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ContactMessages, lv_color_hex(0), 0);
    lv_obj_set_style_bg_opa(ui_ContactMessages, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_ContactMessages, 0, 0);
    lv_obj_set_style_outline_width(ui_ContactMessages, 0, 0);
    lv_obj_set_style_shadow_width(ui_ContactMessages, 0, 0);
    //lv_obj_set_scrollbar_mode(ui_ContactMessages, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_opa(ui_ContactMessages, LV_OPA_TRANSP, LV_PART_ITEMS);
    lv_obj_set_style_border_width(ui_ContactMessages, 0, LV_PART_ITEMS);
    
    lv_obj_t *divider = lv_obj_create(ui_TabPageContacts);
    lv_obj_set_size(divider, 2, 400);
    lv_obj_set_pos(divider, 222, 0); // align between lists
    lv_obj_set_style_bg_color(divider, lv_color_hex(0x444444), 0);
    lv_obj_set_style_border_width(divider, 0, 0);
    lv_obj_set_style_radius(divider, 0, 0);

    #if defined(LANG_EN)
    ui_TabPageChannels = lv_tabview_add_tab(ui_TabView1, "Channels");
    #elif defined(LANG_GR)
    ui_TabPageChannels = lv_tabview_add_tab(ui_TabView1, "Κανάλια");
    #endif

    ui_Channels = lv_dropdown_create(ui_TabPageChannels);
    lv_dropdown_set_options(ui_Channels, "Public");
    lv_obj_set_width(ui_Channels, 291);
    lv_obj_set_height(ui_Channels, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Channels, -243);
    lv_obj_set_y(ui_Channels, -182);
    lv_obj_set_align(ui_Channels, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Channels, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ChannelMessages = lv_list_create(ui_TabPageChannels);
    //lv_list_set_options(ui_ChannelMessages, "Contact", LV_list_MODE_NORMAL);
    lv_obj_set_width(ui_ChannelMessages, 780);
    lv_obj_set_height(ui_ChannelMessages, 342);
    lv_obj_set_x(ui_ChannelMessages, 0);
    lv_obj_set_y(ui_ChannelMessages, 30);
    lv_obj_set_align(ui_ChannelMessages, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ChannelMessages, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(ui_ChannelMessages, 6, 0);
    lv_obj_set_style_pad_all(ui_ChannelMessages, 6, 0);
    lv_obj_set_flex_align(ui_ChannelMessages,
        LV_FLEX_ALIGN_START,
        LV_FLEX_ALIGN_START,
        LV_FLEX_ALIGN_START);

    #if defined(LANG_EN)
    ui_TabPageSettings = lv_tabview_add_tab(ui_TabView1, "Settings");
    #elif defined(LANG_GR)
    ui_TabPageSettings = lv_tabview_add_tab(ui_TabView1, "Ρυθμίσεις");
    #endif

    ui_DayLight = lv_checkbox_create(ui_TabPageSettings);
    #if defined(LANG_EN)
    lv_checkbox_set_text(ui_DayLight, "Day light (summer time)");
    #elif defined(LANG_GR)
    lv_checkbox_set_text(ui_DayLight, "Θερινή ώρα");
    #endif
    lv_obj_set_style_text_font(ui_DayLight, &lv_font_arial_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_width(ui_DayLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DayLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DayLight, -257);
    lv_obj_set_y(ui_DayLight, -168);
    lv_obj_set_align(ui_DayLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DayLight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DayLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DayLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DayLight, event_handler, LV_EVENT_ALL, NULL);
    lv_obj_add_state(ui_DayLight, LV_STATE_DEFAULT);

    ui_DimOverlay = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_DimOverlay);             // no border/padding
    lv_obj_set_size(ui_DimOverlay, LV_PCT(100), LV_PCT(100));
    lv_obj_set_align(ui_DimOverlay, LV_ALIGN_CENTER);

    // black semi transparent background
    lv_obj_set_style_bg_color(ui_DimOverlay, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(ui_DimOverlay, 0, 0);       // initially "off"

    // Do not block touch/scroll
    lv_obj_clear_flag(ui_DimOverlay, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_DimOverlay, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_clear_flag(ui_DimOverlay, LV_OBJ_FLAG_SCROLL_CHAIN_HOR);
    lv_obj_clear_flag(ui_DimOverlay, LV_OBJ_FLAG_SCROLL_CHAIN_VER);

    // always in front
    lv_obj_move_foreground(ui_DimOverlay);

}

void setNightMode(bool night) {

    if (!ui_DimOverlay) return;
    if (night) {
        lv_obj_set_style_bg_opa(ui_DimOverlay, 192, 0);  // 75% dark
    } else {
        lv_obj_set_style_bg_opa(ui_DimOverlay, 0, 0);    // none
    }
}

// void ui_Screen1_screen_init(void)
// {
//     ui_Screen1 = lv_obj_create(NULL);
//     lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
//     lv_obj_set_width(ui_TabView1, 800);
//     lv_obj_set_height(ui_TabView1, 480);
//     lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
//     lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x424242),
//                               LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xFFFFFF),
//                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &lv_font_arial_18,
//                                LV_PART_ITEMS | LV_STATE_DEFAULT);

//     ui_TabPageContacts = lv_tabview_add_tab(ui_TabView1, "Contacts");

//     ui_Contacts = lv_list_create(ui_TabPageContacts);
//     //lv_list_set_options(ui_Contacts, "Contact", LV_list_MODE_NORMAL);
//     lv_obj_set_width(ui_Contacts, 246);
//     lv_obj_set_height(ui_Contacts, 400);
//     lv_obj_set_x(ui_Contacts, -262);
//     lv_obj_set_y(ui_Contacts, 0);
//     lv_obj_set_align(ui_Contacts, LV_ALIGN_CENTER);

//     ui_ContactMessages = lv_list_create(ui_TabPageContacts);
//     //lv_list_set_options(ui_ContactMessages, "Contact", LV_list_MODE_NORMAL);
//     lv_obj_set_width(ui_ContactMessages, 500);
//     lv_obj_set_height(ui_ContactMessages, 400);
//     lv_obj_set_x(ui_ContactMessages, 124);
//     lv_obj_set_y(ui_ContactMessages, 0);
//     lv_obj_set_align(ui_ContactMessages, LV_ALIGN_CENTER);
//     lv_obj_set_style_bg_color(ui_ContactMessages, lv_color_hex(0), 0);

//     ui_TabPageChannels = lv_tabview_add_tab(ui_TabView1, "Channels");

//     ui_Channels = lv_dropdown_create(ui_TabPageChannels);
//     lv_dropdown_set_options(ui_Channels, "Public");
//     lv_obj_set_width(ui_Channels, 291);
//     lv_obj_set_height(ui_Channels, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Channels, -243);
//     lv_obj_set_y(ui_Channels, -182);
//     lv_obj_set_align(ui_Channels, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_Channels, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



//     ui_ChannelMessages = lv_list_create(ui_TabPageChannels);
//     //lv_list_set_options(ui_ChannelMessages, "Contact", LV_list_MODE_NORMAL);
//     lv_obj_set_width(ui_ChannelMessages, 780);
//     lv_obj_set_height(ui_ChannelMessages, 342);
//     lv_obj_set_x(ui_ChannelMessages, 0);
//     lv_obj_set_y(ui_ChannelMessages, 30);
//     lv_obj_set_align(ui_ChannelMessages, LV_ALIGN_CENTER);
//     lv_obj_set_flex_flow(ui_ChannelMessages, LV_FLEX_FLOW_COLUMN);
//     lv_obj_set_style_pad_row(ui_ChannelMessages, 6, 0);
//     lv_obj_set_style_pad_all(ui_ChannelMessages, 6, 0);
//     lv_obj_set_flex_align(ui_ChannelMessages,
//         LV_FLEX_ALIGN_START,
//         LV_FLEX_ALIGN_START,
//         LV_FLEX_ALIGN_START);


//     ui_TabPageSettings = lv_tabview_add_tab(ui_TabView1, "Settings");

//     ui_AutoLight = lv_checkbox_create(ui_TabPageSettings);
//     lv_checkbox_set_text(ui_AutoLight, "Auto dim brightness");
//     lv_obj_set_width(ui_AutoLight, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_AutoLight, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_AutoLight, -257);
//     lv_obj_set_y(ui_AutoLight, -168);
//     lv_obj_set_align(ui_AutoLight, LV_ALIGN_CENTER);
//     lv_obj_add_flag(ui_AutoLight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
//     lv_obj_set_style_text_color(ui_AutoLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_text_opa(ui_AutoLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     lv_obj_add_event_cb(ui_AutoLight, ui_event_AutoLight, LV_EVENT_ALL, NULL);

// }

// void setNightMode(bool night) {

//     if (!ui_DimOverlay) return;
//     if (night) {
//         lv_obj_set_style_bg_opa(ui_DimOverlay, 192, 0);  // 75% dark
//     } else {
//         lv_obj_set_style_bg_opa(ui_DimOverlay, 0, 0);    // none
//     }
// }
