// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 800);
    lv_obj_set_height(ui_TabView1, 480);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x424242),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &lv_font_montserrat_18,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TabPageContacts = lv_tabview_add_tab(ui_TabView1, "Contacts");

    ui_Contacts = lv_roller_create(ui_TabPageContacts);
    lv_roller_set_options(ui_Contacts, "Contact", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Contacts, 246);
    lv_obj_set_height(ui_Contacts, 400);
    lv_obj_set_x(ui_Contacts, -262);
    lv_obj_set_y(ui_Contacts, 0);
    lv_obj_set_align(ui_Contacts, LV_ALIGN_CENTER);

    ui_ContactMessages = lv_roller_create(ui_TabPageContacts);
    lv_roller_set_options(ui_ContactMessages, "Contact", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_ContactMessages, 500);
    lv_obj_set_height(ui_ContactMessages, 400);
    lv_obj_set_x(ui_ContactMessages, 124);
    lv_obj_set_y(ui_ContactMessages, 0);
    lv_obj_set_align(ui_ContactMessages, LV_ALIGN_CENTER);

    ui_TabPageChannels = lv_tabview_add_tab(ui_TabView1, "Channels");

    ui_Channels = lv_dropdown_create(ui_TabPageChannels);
    lv_dropdown_set_options(ui_Channels, "Public");
    lv_obj_set_width(ui_Channels, 291);
    lv_obj_set_height(ui_Channels, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Channels, -243);
    lv_obj_set_y(ui_Channels, -182);
    lv_obj_set_align(ui_Channels, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Channels, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_ChannelMessages = lv_roller_create(ui_TabPageChannels);
    lv_roller_set_options(ui_ChannelMessages, "Contact", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_ChannelMessages, 780);
    lv_obj_set_height(ui_ChannelMessages, 342);
    lv_obj_set_x(ui_ChannelMessages, 0);
    lv_obj_set_y(ui_ChannelMessages, 30);
    lv_obj_set_align(ui_ChannelMessages, LV_ALIGN_CENTER);

    ui_TabPageSettings = lv_tabview_add_tab(ui_TabView1, "Settings");

    ui_AutoLight = lv_checkbox_create(ui_TabPageSettings);
    lv_checkbox_set_text(ui_AutoLight, "Auto dim brightness");
    lv_obj_set_width(ui_AutoLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AutoLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AutoLight, -257);
    lv_obj_set_y(ui_AutoLight, -168);
    lv_obj_set_align(ui_AutoLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AutoLight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_AutoLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AutoLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_AutoLight, ui_event_AutoLight, LV_EVENT_ALL, NULL);

}
